#!/usr/bin/env bash
# Write the task list of this campaign for etc/oniom/worker.sh: ./tasks.sh > tasks.txt
# One task per job of jobs.txt. shellres jobs use the double-precision build ($GMX_D), the
# others the single-precision GPU build ($GMX). After each job the summary is rewritten,
# under a lock as several workers share it.
set -euo pipefail
cd "$(dirname "$0")"
echo "# generated by tasks.sh from jobs.txt"
while read -r name box ml seed; do
    [[ -z $name || $name == \#* ]] && continue
    gmx='$GMX'
    [[ $ml == shellres ]] && gmx='$GMX_D'
    echo "$name GMX=$gmx ./run_job.sh $name $box $ml $seed && flock summary.lock \$ONIOM_PY summarize.py > /dev/null"
done < jobs.txt
