#!/usr/bin/env bash
# The whole solute (protein + four hemes, 9,026 atoms) as ML, water and ions MM: ONIOM NVT (2 ps)
# then NVE (5 ps) from a replica's MM NpT, the protocol of the heme-site runs in run.sh.
#
#   ./allml.sh RUN_DIR MODEL    MODEL is a file in $ONIOM_MODELS without .pt, e.g. pet-mad-s-v1.5.0
#
# Runs in RUN_DIR/allml-MODEL/ and needs RUN_DIR's npt stage and SOLUTE group (run.sh makes both).
# PET-OMol models get the solute as one system: charge -6 (the topology's net charge) and
# multiplicity ALLML_SPIN (default 1: the four high-spin Fe(II) paired antiparallel). Aligned
# spins (17) are out of PET-OMol's range, 1-11; the electron count (34,328) is even.
# The mdp files are the site ones with ML -> SOLUTE and no link atoms (no bonds are cut).
# Memory on an H100 (models/fit_test.py): PET-MAD xs 5.5 GiB, s 19, m 76; PET-OMol s 18, m 62.
set -euo pipefail
HB=$(cd "$(dirname "$0")" && pwd)
. "$HB/../etc/oniom/env.sh"
RUN=$(realpath "$1") MODEL=$2 SPIN=${ALLML_SPIN:-1}
cd "$RUN"
[[ -f npt.cpt ]] && grep -q '\[ SOLUTE \]' index.ndx || { echo "$RUN: npt or SOLUTE missing" >&2; exit 2; }
D=allml-$MODEL
mkdir -p "$D"
gmx() { "$GMX" "$@"; }

mdp() {  # mdp SITE_MDP OUT: the site mdp turned into the whole-solute one for MODEL
    sed -e "s|pet-[a-z]*-[a-z]*-v[0-9.]*\.pt|$MODEL.pt|" \
        -e "s|^metatomic-input-group .*|metatomic-input-group   = SOLUTE|" \
        -e "/^metatomic-link-atoms/d" -e "/^metatomic-site-/d" -e "/^; four separate/,/^; high-spin/d" \
        -e "s|^; ONIOM: .*|; ONIOM: the whole solute (group SOLUTE) as ML, CHARMM27 water and ions|" \
        -e "1s|.*|; whole solute as ML with $MODEL (generated by allml.sh)|" "$1" > "$2"
    if [[ $MODEL == pet-omol* ]]; then
        printf '%s\n' "; the solute as one system: net charge -6, spin multiplicity $SPIN" \
            "metatomic-site-groups   = SOLUTE" "metatomic-site-charges  = -6" \
            "metatomic-site-spin-multiplicities = $SPIN" >> "$2"
    fi
    oniom_mdp "$2" "$2.tmp" && mv "$2.tmp" "$2"
}

step() {  # step NAME SITE_MDP [grompp args]: one stage, skipped once done, resumed from its checkpoint
    [[ -f $D/$1.gro ]] && return
    local omol=; [[ $MODEL == pet-omol* ]] && omol=_omol
    mdp "$HB/mdp/$2$omol.mdp" "$D/$1.mdp"
    [[ -f $D/$1.tpr ]] || gmx grompp -f "$D/$1.mdp" -p topol.top -n index.ndx -o "$D/$1.tpr" \
        -po "$D/$1.mdout.mdp" "${@:3}"
    local cpi=(); [[ -f $D/$1.cpt ]] && cpi=(-cpi "$D/$1.cpt")
    gmx mdrun -deffnm "$D/$1" -nt "$NT" "${cpi[@]}"
}

step nvt onvt -c npt.gro -t npt.cpt
step nve onve -c "$D/nvt.gro" -t "$D/nvt.cpt"
